#!/bin/sh

## live-debconfig(7) - System Configuration Scripts
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

. /usr/share/debconf/confmodule

Defaults ()
{
	_LO_ENABLE="${_LO_ENABLE:-true}"
	_ETH0_METHOD="${_ETH0_METHOD:-dhcp}"
	_ETH0_ADDRESS="${_ETH0_ADDRESS:-192.168.1.2}"

	if [ -e /etc/resolv.conf ]
	then
		_NAMESERVER_ADDRESSES="${_NAMESERVER_ADDRESSES:-$(awk '/^nameserver / {$1=""; print $0}' /etc/resolv.conf)}"
		_NAMESERVER_DOMAIN="${_NAMESERVER_DOMAIN:-$(awk '/^domain / {$1=""; print $0}' /etc/resolv.conf)}"
		_NAMESERVER_SEARCH="${_NAMESERVER_SEARCH:-$(awk '/^search / {$1=""; print $0}' /etc/resolv.conf)}"
		_NAMESERVER_OPTIONS="${_NAMESERVER_OPTIONS:-$(awk '/^options / {$1=""; print $0}' /etc/resolv.conf)}"
	fi
}

db_get live-debconfig/ifupdown/lo-enable
_LO_ENABLE="${RET}" # boolean

db_get live-debconfig/ifupdown/lo-comment
_LO_COMMENT="${RET}" # string (w/empty)

db_get live-debconfig/ifupdown/eth0-method
_ETH0_METHOD="${RET}" # select

db_get live-debconfig/ifupdown/eth0-comment
_ETH0_COMMENT="${RET}" # string (w/ empty)

db_get live-debconfig/ifupdown/eth0-address
_ETH0_ADDRESS="${RET}" # string (w/o empty)

db_get live-debconfig/ifupdown/eth0-broadcast
_ETH0_BROADCAST="${RET}" # string (w/ empty)

db_get live-debconfig/ifupdown/eth0-gateway
_ETH0_GATEWAY="${RET}" # string (w/ empty)

db_get live-debconfig/ifupdown/eth0-netmask
_ETH0_NETMASK="${RET}" # string (w/ empty)

db_get live-debconfig/ifupdown/eth0-network
_ETH0_NETWORK="${RET}" # string (w/ empty)

db_get live-debconfig/ifupdown/nameserver-addresses
_NAMESERVER_ADDRESSES="${RET}" # string (w/ empty)

db_get live-debconfig/ifupdown/nameserver-domain
_NAMESERVER_DOMAIN="${RET}" # string (w/ empty)

dg_get live-debconfig/ifupdown/nameserver-search
_NAMESERVER_SEARCH="${RET}" # string (w/ empty)

db_get live-debconfig/ifupdown/nameserver-options
_NAMESERVER_OPTIONS="${RET}" # string (w/ empty)

Defaults

db_set live-debconfig/ifupdown/lo-enable "${_LO_ENABLE}"
db_fset live-debconfig/ifupdown/lo-enable seen false

db_set live-debconfig/ifupdown/lo-comment "${_LO_COMMENT}"
db_fset live-debconfig/ifupdown/lo-comment seen false

db_set live-debconfig/ifupdown/eth0-method "${_ETH0_METHOD}"
db_fset live-debconfig/ifupdown/eth0-method seen false

db_set live-debconfig/ifupdown/eth0-comment "${_ETH0_COMMENT}"
db_fset live-debconfig/ifupdown/eth0-comment seen false

db_set live-debconfig/ifupdown/eth0-address "${_ETH0_ADDRESS}"
db_fset live-debconfig/ifupdown/eth0-address seen false

db_set live-debconfig/ifupdown/eth0-broadcast "${_ETH0_BROADCAST}"
db_fset live-debconfig/ifupdown/eth0-broadcast seen false

db_set live-debconfig/ifupdown/eth0-gateway "${_ETH0_GATEWAY}"
db_fset live-debconfig/ifupdown/eth0-gateway seen false

db_set live-debconfig/ifupdown/eth0-netmask "${_ETH0_NETMASK}"
db_fset live-debconfig/ifupdown/eth0-netmask seen false

db_set live-debconfig/ifupdown/eth0-network "${_ETH0_NETWORK}"
db_fset live-debconfig/ifupdown/eth0-network seen false

db_set live-debconfig/ifupdown/nameserver-addresses "${_NAMESERVER_ADDRESSES}"
db_fset live-debconfig/ifupdown/nameserver-addresses seen false

db_set live-debconfig/ifupdown/nameserver-domain "${_NAMESERVER_DOMAIN}"
db_fset live-debconfig/ifupdown/nameserver-domain seen false

db_set live-debconfig/ifupdown/nameserver-search "${_NAMESERVER_SEARCH}"
db_fset live-debconfig/ifupdown/nameserver-search seen false

db_set live-debconfig/ifupdown/nameserver-options "${_NAMESERVER_OPTIONS}"
db_fset live-debconfig/ifupdown/nameserver-options seen false

db_settitle live-debconfig/title
db_input high live-debconfig/ifupdown/lo-enable || true
db_go

db_get live-debconfig/ifupdown/lo-enable
_LO_ENABLE="${RET}" # boolean

db_get live-debconfig/ifupdown/lo-comment
_LO_COMMENT="${RET}" # string (w/ empty)

db_settitle live-debconfig/title
db_input high live-debconfig/ifupdown/eth0-method || true
db_go

db_get live-debconfig/ifupdown/eth0-method
_ETH0_METHOD="${RET}" # select

case "${_ETH0_METHOD}" in
	none|dhcp)

		;;

	static)
		db_setttile live-debconfig/title
		dh_input high live-debconfig/ifupdown/eth0-comment || true
		db_go

		db_settitle live-debconfig/title
		db_input high live-debconfig/ifupdown/eth0-address || true
		db_go

		db_settitle live-debconfig/title
		db_input high live-debconfig/ifupdown/eth0-broadcast || true
		db_go

		db_settitle live-debconfig/title
		db_input high live-debconfig/ifupdown/eth0-gateway || true
		db_go

		db_settitle live-debconfig/title
		db_input high live-debconfig/ifupdown/eth0-netmask || true
		db_go

		db_settitle live-debconfig/title
		db_input high live-debconfig/ifupdown/eth0-network || true
		db_go

		db_settitle live-debconfig/title
		db_input high live-debconfig/ifupdown/nameserver-addresses || true
		db_go
		;;
esac

_NUMBER="0"

while db_get live-debconfig/ifupdown/eth${_NUMBER}-method && [ "${RET}" ]
do
	if db_get live-debconfig/ifupdown/eth${_NUMBER}-comment
	then
		eval _ETH${_NUMBER}_COMMENT="\"${RET}\"" # string (w/ empty)
	fi

	if db_get live-debconfig/ifupdown/eth${_NUMBER}-method
	then
		eval _ETH${_NUMBER}_METHOD="\"${RET}\"" # select
	fi

	if db_get live-debconfig/ifupdown/eth${_NUMBER}-address
	then
		eval _ETH${_NUMBER}_ADDRESS="\"${RET}\"" # string (w/o empty)
	fi

	if db_get live-debconfig/ifupdown/eth${_NUMBER}-broadcast
	then
		eval _ETH${_NUMBER}_BROADCAST="\"${RET}\"" # string (w/ empty)
	fi

	if db_get live-debconfig/ifupdown/eth${_NUMBER}-gateway
	then
		eval _ETH${_NUMBER}_GATEWAY="\"${RET}\"" # string (w/ empty)
	fi

	if db_get live-debconfig/ifupdown/eth${_NUMBER}-netmask
	then
		eval _ETH${_NUMBER}_NETMASK="\"${RET}\"" # string (w/ empty)
	fi

	if db_get live-debconfig/ifupdown/eth${_NUMBER}-network
	then
		eval _ETH${_NUMBER}_NETWORK="\"${RET}\"" # string (w/ empty)
	fi

	_NUMBER="$((${_NUMBER} + 1))"
done

_ETH_NUMBER="${_NUMBER}"

db_get live-debconfig/ifupdown/nameserver-addresses
_NAMESERVER_ADDRESSES="${RET}" # string (w/ empty)

db_get live-debconfig/ifupdown/nameserver-domain
_NAMESERVER_DOMAIN="${RET}" # string (w/ empty)

db_get live-debconfig/ifupdown/nameserver-search
_NAMESERVER_SEARCH="${RET}" # string (w/ empty)

db_get live-debconfig/ifupdown/nameserver-options
_NAMESERVER_OPTIONS="${RET}" # string (w/ empty)

Defaults

db_stop

# Create /etc/network/interfaces

cat > /etc/network/interfaces.tmp << EOF
# Used by ifup(8) and ifdown(8). See the interfaces(5) manpage or
# /usr/share/doc/ifupdown/examples for more information.

EOF

case "${_LO_ENABLE}" in
	true)
		if [ -n "${_LO_COMMENT}" ]
		then
			echo "# ${_LO_COMMENT}" >> /etc/network/interfaces.tmp
		fi

cat >> /etc/network/interfaces.tmp << EOF
auto lo
iface lo inet loopback
EOF

		;;
esac

for _NUMBER in $(seq 0 ${_ETH_NUMBER})
do
	eval _COMMENT="$`echo _ETH${_NUMBER}_COMMENT`"
	eval _METHOD="$`echo _ETH${_NUMBER}_METHOD`"
	eval _ADDRESS="$`echo _ETH${_NUMBER}_ADDRESS`"
	eval _BROADCAST="$`echo _ETH${_NUMBER}_BROADCAST`"
	eval _GATEWAY="$`echo _ETH${_NUMBER}_GATEWAY`"
	eval _NETMASK="$`echo _ETH${_NUMBER}_NETMASK`"
	eval _NETWORK="$`echo _ETH${_NUMBER}_NETWORK`"

	if [ -z "${_METHOD}" ]
	then
		continue
	fi

	echo >> /etc/network/interfaces.tmp

	if [ -n "${_COMMENT}" ]
	then
		echo "# ${_COMMENT}" >> /etc/network/interfaces.tmp
	fi

	case "${_METHOD}" in
		none)

cat >> /etc/network/interfaces.tmp << EOF
iface eth${_NUMBER} inet manual
EOF

			;;

		dhcp)

cat >> /etc/network/interfaces.tmp << EOF
auto eth${_NUMBER}
iface eth${_NUMBER} inet dhcp
EOF

			;;

		static)

cat >> /etc/network/interfaces.tmp << EOF
auto eth${_NUMBER}
iface eth${_NUMBER} inet static
	address		${_ADDRESS}
EOF

			if [ -n "${_BROADCAST}" ]
			then
				echo "	broadcast	${_BROADCAST}" >> /etc/network/interfaces.tmp
			fi

			if [ -n "${_GATEWAY}" ]
			then
				echo "	gateway		${_GATEWAY}" >> /etc/network/interfaces.tmp
			fi

			if [ -n "${_NETMASK}" ]
			then
				echo "	netmask		${_NETMASK}" >> /etc/network/interfaces.tmp
			fi

			if [ -n "${_NETWORK}" ]
			then
				echo "	network		${_NETWORK}" >> /etc/network/interfaces.tmp
			fi
			;;
	esac

	_NUMBER="$((${_NUMBER} + 1))"
done

mv /etc/network/interfaces.tmp /etc/network/interfaces

# Create /etc/resolv.conf
rm -f /etc/resolv.conf.tmp

if [ -n "${_NAMESERVER_DOMAIN}" ]
then
	echo "domain ${_NAMESERVER_DOMAIN}" >> /etc/resolv.conf.tmp
fi

if [ -n "${_NAMESERVER_SEARCH}" ]
then
	echo "search ${_NAMESERVER_SEARCH}" >> /etc/resolv.conf.tmp
fi

if [ -n "${_NAMESERVER_ADDRESSES}" ]
then
	for _NAMESERVER_ADDRESS in $(echo ${_NAMESERVER_ADDRESSES} | sed -e 's|,| |g')
	do
		echo "nameserver ${_NAMESERVER_ADDRESS}" >> /etc/resolv.conf.tmp
	done
fi

if [ -n "${_NAMESERVER_OPTIONS}" ]
then
	echo "options ${_NAMESERVER_OPTIONS}" >> /etc/resolv.conf.tmp
fi

mv /etc/resolv.conf.tmp /etc/resolv.conf

# Create /etc/hosts
case "${_ETH0_METHOD}" in
	none|dhcp)

cat > /etc/hosts.tmp << EOF
127.0.0.1	localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

		;;

	static)

cat > /etc/hosts.tmp << EOF
127.0.0.1	localhost
${_ETH0_ADDRESS}	$(cat /etc/hostname)

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

		;;
esac

mv /etc/hosts.tmp /etc/hosts
