#!/bin/sh

## live-debconfig(7) - System Configuration Scripts
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

. /usr/share/debconf/confmodule

Defaults ()
{
	if [ -z "${_SELINUX_ENABLE}" ]
	then
		if [ -n "$(cat /selinux/enforce 2> /dev/null)" ]
		then
			case "$(cat /selinux/enforce 2> /dev/null)" in
				0)
					_SELINUX_ENABLE="false"
					;;

				1)
					_SELINUX_ENABLE="true"
					;;
			esac
		else
			_SELINUX_ENABLE="false"
		fi
	fi
}

db_get live-debconfig/selinux/enable
_SELINUX_ENABLE="${RET}" # boolean

Defaults

db_set live-debconfig/selinux/enable "${_SELINUX_ENABLE}"
db_fset live-debconfig/selinux/enable seen false

db_settitle live-debconfig/title
db_input high live-debconfig/selinux/enable || true
db_go

db_get live-debconfig/selinux/enable
_SELINUX_ENABLE="${RET}" # boolean

Defaults

db_stop

case "${_SELINUX_ENABLE}" in
	true)
		rm -f /selinux/enforce
		rmdir --ignore-fail-on-non-empty /selinux > /dev/null 2>&1 || true
		;;

	false)
		mkdir -p /selinux
		echo 0 > /selinux/enforce
		;;
esac
