#!/bin/sh

## live-debconfig contains the components that configure a Live system during the
## build process (live-build).
##
## This is the sysvinit component for live-debconfig.


### BEGIN INIT INFO
# Provides:		live-debconfig
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:
# Default-Stop:		0 6
# Short-Description:	Live System Configuration Components
# Description:		live-debconfig contains the components that configure a
#			Live system during the build process (live-build).
# X-Start-Before:
# X-Stop-After:
# X-Interactive:
### END INIT INFO

exit 0
