.\" live-debconfig(7) - System Configuration Components
.\" Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
.\"
.\" This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
.\" This is free software, and you are welcome to redistribute it
.\" under certain conditions; see COPYING for details.
.\"
.\"
.TH LIVE\-DEBCONFIG 1 2014\-07\-22 4.0~alpha35-1 "Live Systems Project"

.SH NAME
\fBlive\-debconfig\-get\-selections\fR \- output contents of the live\-debconfig(7) debconf database

.SH SYNOPSIS
\fBlive\-debconfig\-get\-selections\fR

.SH DESCRIPTION
\fBlive\-debconfig\-get\-selections\fR outputs the content of the live\-debconfig(7) debconf database in a format understandable by debconf\-set\-selections(1).

.SH OPTIONS
\fBlive\-debconfig\-get\-selections\fR has no options.

.SH FILES
.IP "\fB/var/lib/live/debconfig/systemrc\fR" 4
.IP "\fB/var/lib/live/debconfig/config.dat\fR" 4
.IP "\fB/var/lib/live/debconfig/passwords.dat\fR" 4
.IP "\fB/var/lib/live/debconfig/templates.dat\fR" 4

.SH SEE ALSO
\fIdebconf\-get\-selections\fR(1)
.PP
\fIlive\-debconfig\fR(7)

.SH HOMEPAGE
More information about live\-debconfig and the Live Systems project can be found on the homepage at <\fIhttp://live-systems.org/\fR> and in the manual at <\fIhttp://live-systems.org/manual/\fR>.

.SH BUGS
Bugs can be reported by submitting a bugreport for the live\-debconfig package in the Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the Live Systems mailing list at <\fIdebian\-live@lists.debian.org\fR>.

.SH AUTHOR
live\-debconfig was written by Daniel Baumann <\fImail@daniel-baumann.ch\fR>.
